@startuml

skinparam classAttributeIconSize 0

class Body {
- position : Vector
- velocity : Vector
- mass : double
+ move(f:Vector, dt:double)
+ forceFrom(b : Body) : Vector
+ toString()
}

class Vector {
- numberOfBodies : int
- data : double[]
+ Vector(numberOfBodies:int)
+ length() : int
+ dot(otherVector: Vector)
+ magnitude() : double
+ euclideanDistanceTo(otherVector: Vector)
+ plus (vectorToAdd: Vector) : Vector
+ minus (VectorToSubstract: Vector) : Vector
+ cartesian(i:int) : double
+ times(factor:double) : Vector
+ scale(factor:double)
+ toString()
}

class Universe {
- numberOfBodies : int
- bodies : Body[]
- Universe(fname : String)
+ getNumberOfBodies() : int
+ getBodies() : Body[]
+ increaseTimeByTraveledDistance(dt : double)
- initCelestialBodies(Scanner in)
}

class NBodySimulator {
+ startSimulation(distance : double, universe : Universe, showPlanetaryTrace : boolean, pause : int)
    + {static} main()
    + {static} drawUniverse()
   - drawBody(r : Vector, penRadius : double)
}

NBodySimulator "1" -> Universe
Universe "1 *" *-- Body : bodies
Body -> Vector

note top of Vector
This can't be a java.util.Vector class
endnote

note right of NBodySimulator
  private static void startSimulation(double distance, Universe universe,boolean showPlanetaryTrace,int pause) {
    StdDraw.enableDoubleBuffering();

    while (true) {
      if (!showPlanetaryTrace) {
        StdDraw.clear();
      }

      universe.increaseTimeByTraveledDistance(distance);
      drawUniverse();
      StdDraw.show();
      StdDraw.pause(pause);
    }
  }
endnote


@enduml